version: "3"

services:
  postgres:
    image: "postgres:13.1"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432

  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  box:
    image: busybox
    volumes:
      - /box

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebittwitter
    environment: 
      - BUNDLE_PATH=/box
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes_from:
    - box

volumes:
  redis:
  postgres:
  box: